name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Build
        run: go build -v .
      - name: Get doduda
        run: |
          curl -s https://api.github.com/repos/dofusdude/doduda/releases/latest \
          | grep "browser_download_url.*Linux_x86_64.tar.gz" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -qi -
          tar -xzf doduda_Linux_x86_64.tar.gz
          chmod +x doduda
      - name: Get required files for testing
        run: |
          sudo apt install curl -y
          mkdir persistent
          curl -sL https://raw.githubusercontent.com/dofusdude/doduda/main/persistent/elements.dofus3.main.json -o persistent/elements.dofus3.main.json
          curl -sL https://raw.githubusercontent.com/dofusdude/doduda/main/persistent/item_types.dofus3.main.json -o persistent/item_types.dofus3.main.json
          ./doduda -i 'images-*' -c
      - name: Test
        run: go test -v
